services:
  - type: web
    name: app.py
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn -w 4 -b :10000 app:app 
    envVars:
      - key: PATH
        value: $PATH:/opt/render/.local/bin
    region: oregon
