services:
- type: web
  name: flask-app
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: python -m gunicorn -w 4 -b :10000 app:app
  envVars:
    - key: FLASK_APP
      value: app.py
    - key: FLASK_ENV
      value: production 
  region: oregon
