services:
  - type: web
    name: app.py
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b :10000 app:app
    envVars:
      - key: FLASK_ENV
        value: production
    region: oregon
