services:
- type: web
  name: flask-app
  env: python
  buildCommand: cd tutorial5 && pip install -r requirements.txt
  startCommand: cd tutorial5 && gunicorn -w 4 -b :10000 app:app
  envVars:
    - key: FLASK_ENV
      value: production
  region: oregon
